# Generated by Django 4.2 on 2023-04-08 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("scores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="date_submitted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
